Name:           ros-kinetic-rostune
Version:        1.0.7
Release:        0%{?dist}
Summary:        ROS rostune package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rostune
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-message-runtime
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-topic-tools
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-message-generation
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-topic-tools

%description
rostune is a tool that helps ROS developers distribute their nodes in the most
effective way. It collects statistics for topics and nodes, such as CPU and
network usage.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Nov 01 2017 George Stavrinos <gstavrinos@iit.demokritos.gr> - 1.0.7-0
- Autogenerated by Bloom

* Wed Nov 01 2017 George Stavrinos <gstavrinos@iit.demokritos.gr> - 1.0.6-0
- Autogenerated by Bloom

* Thu Jul 13 2017 George Stavrinos <gstavrinos@iit.demokritos.gr> - 1.0.5-1
- Autogenerated by Bloom

* Tue Jul 11 2017 George Stavrinos <gstavrinos@iit.demokritos.gr> - 1.0.5-0
- Autogenerated by Bloom

* Tue Jul 11 2017 George Stavrinos <gstavrinos@iit.demokritos.gr> - 1.0.4-0
- Autogenerated by Bloom

* Tue Jul 11 2017 George Stavrinos <gstavrinos@iit.demokritos.gr> - 1.0.2-0
- Autogenerated by Bloom

